apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-kubernetes-component
  namespace: test
  annotations:
    backstage.io/kubernetes-namespace: test
    backstage.io/kubernetes-id: my-kubernetes-component
    janus-idp.io/tekton: my-kubernetes-component
    janus-idp.io/tekton-pipeline: simple-pipeline
    janus-idp.io/tekton-task: deploy-nginx-task
    # backstage.io/kubernetes-label-selector: 'backstage.io/kubernetes-id=my-kubernetes-component'
    jenkins.io/job-full-name: 'default:orgnew/test'
    backstage.io/kubernetes-auth-provider: serviceAccount
    janus-idp.io/tekton-pipelinerun: my-kubernetes-component-pipelinerun
    nexus-repository-manager/docker.image-name: 'nexus-docker/nexus3'
    servicenow.com/entity-id: my-kubernetes-component
    npm/package: react
  labels:
    backstage.io/kubernetes-id: my-kubernetes-component
  tags:
    - java
    - mobile
spec:
  lifecycle: production
  owner: rhdh-ui-test
  type: service
