apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-kubernetes-component
  namespace: default
  annotations:
    backstage.io/kubernetes-id: my-kubernetes-component
    janus-idp.io/tekton: my-kubernetes-component
    backstage.io/kubernetes-label-selector: 'app=my-app,component=front-end'
    jenkins.io/job-full-name: 'default:orgnew/test'
  labels:
    backstage.io/kubernetes-id: my-kubernetes-component
  tags:
    - java
    - mobile
spec:
  lifecycle: production
  owner: team_a
  type: service
